// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package authenticate

import (
	user "users/user"

	mock "github.com/stretchr/testify/mock"
)

// MockFinder is an autogenerated mock type for the Finder type
type MockFinder struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: _a0
func (_m *MockFinder) FindOne(_a0 string) (user.User, error) {
	ret := _m.Called(_a0)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
