FROM node:14-alpine as app
RUN apk add --no-cache g++ make python
WORKDIR /usr/src/app
COPY app/package*.json ./
RUN npm ci
COPY app .env ./
ENV NODE_ENV=production
RUN npm run build

FROM lewislbr/gss:latest
COPY --from=app /usr/src/app/dist ./dist
