FROM golang:1-alpine AS builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
ENV MODE=production
RUN go build -ldflags="-s -w" main.go

FROM alpine:latest AS certs
RUN apk --no-cache add ca-certificates

FROM scratch AS app
COPY --from=builder /build/main ./
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/main"]
