version: "3"

services:
  plants:
    build:
      context: plants
      target: dev
    image: plantdex/plants:dev
    container_name: plants
    env_file:
      - plants/.env
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true

  users:
    build:
      context: users
      target: dev
    image: plantdex/users:dev
    container_name: users
    env_file:
      - users/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/plantdex-dev-local-key.json
    ports:
      - "8082:8080"
    volumes:
      - ./users/plantdex-dev-local-key.json:/tmp/keys/plantdex-dev-local-key.json:ro
    stdin_open: true
    tty: true

  web:
    build:
      context: web
      target: dev
    image: plantdex/web:dev
    container_name: web
    env_file:
      - web/.env
    ports:
      - "8080:8080"
    volumes:
      - ./web:/web
