// Code generated by mockery (devel). DO NOT EDIT.

package plant

import mock "github.com/stretchr/testify/mock"

// mockPlantRepo is an autogenerated mock type for the plantRepo type
type mockPlantRepo struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *mockPlantRepo) Delete(_a0 string, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: _a0
func (_m *mockPlantRepo) FindAll(_a0 string) ([]Plant, error) {
	ret := _m.Called(_a0)

	var r0 []Plant
	if rf, ok := ret.Get(0).(func(string) []Plant); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Plant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOne provides a mock function with given fields: _a0, _a1
func (_m *mockPlantRepo) FindOne(_a0 string, _a1 string) (Plant, error) {
	ret := _m.Called(_a0, _a1)

	var r0 Plant
	if rf, ok := ret.Get(0).(func(string, string) Plant); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(Plant)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *mockPlantRepo) Insert(_a0 string, _a1 Plant) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, Plant) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockPlantRepo) Update(_a0 string, _a1 string, _a2 Plant) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, string, Plant) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, Plant) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
