FROM golang:1-alpine AS builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
ENV MODE=production
RUN go build -ldflags '-s -w' cmd/server/main.go

FROM scratch as app
COPY --from=builder /build/main ./
ENTRYPOINT ["/main"]
