// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package delete

import mock "github.com/stretchr/testify/mock"

// MockDeleter is an autogenerated mock type for the Deleter type
type MockDeleter struct {
	mock.Mock
}

// DeleteOne provides a mock function with given fields: _a0, _a1
func (_m *MockDeleter) DeleteOne(_a0 string, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
