// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package delete

import mock "github.com/stretchr/testify/mock"

// MockDeleteService is an autogenerated mock type for the DeleteService type
type MockDeleteService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MockDeleteService) Delete(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
