// Code generated by mockery (devel). DO NOT EDIT.

package server

import (
	plant "lewislbr/plantdex/plants/plant"

	mock "github.com/stretchr/testify/mock"
)

// mockPlantService is an autogenerated mock type for the plantService type
type mockPlantService struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *mockPlantService) Add(_a0 string, _a1 plant.Plant) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, plant.Plant) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *mockPlantService) Delete(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Edit provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockPlantService) Edit(_a0 string, _a1 string, _a2 plant.Plant) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, plant.Plant) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAll provides a mock function with given fields: _a0
func (_m *mockPlantService) ListAll(_a0 string) ([]plant.Plant, error) {
	ret := _m.Called(_a0)

	var r0 []plant.Plant
	if rf, ok := ret.Get(0).(func(string) []plant.Plant); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plant.Plant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOne provides a mock function with given fields: _a0, _a1
func (_m *mockPlantService) ListOne(_a0 string, _a1 string) (plant.Plant, error) {
	ret := _m.Called(_a0, _a1)

	var r0 plant.Plant
	if rf, ok := ret.Get(0).(func(string, string) plant.Plant); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(plant.Plant)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
