// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package server

import (
	plant "plants/plant"

	mock "github.com/stretchr/testify/mock"
)

// mockEditer is an autogenerated mock type for the editer type
type mockEditer struct {
	mock.Mock
}

// Edit provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockEditer) Edit(_a0 string, _a1 string, _a2 plant.Plant) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, plant.Plant) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
