// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package add

import (
	plant "plants/plant"

	mock "github.com/stretchr/testify/mock"
)

// MockAddService is an autogenerated mock type for the AddService type
type MockAddService struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *MockAddService) Add(_a0 string, _a1 plant.Plant) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, plant.Plant) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
