// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package add

import (
	plant "plants/plant"

	mock "github.com/stretchr/testify/mock"
)

// MockInserter is an autogenerated mock type for the Inserter type
type MockInserter struct {
	mock.Mock
}

// InsertOne provides a mock function with given fields: _a0, _a1
func (_m *MockInserter) InsertOne(_a0 string, _a1 plant.Plant) (interface{}, error) {
	ret := _m.Called(_a0, _a1)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, plant.Plant) interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, plant.Plant) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
