// Code generated by mockery (devel). DO NOT EDIT.

package token

import mock "github.com/stretchr/testify/mock"

// mockTokenRepo is an autogenerated mock type for the tokenRepo type
type mockTokenRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *mockTokenRepo) Add(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckExists provides a mock function with given fields: _a0
func (_m *mockTokenRepo) CheckExists(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
