// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package edit

import (
	plant "plants/plant"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

// UpdateOne provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUpdater) UpdateOne(_a0 string, _a1 string, _a2 plant.Plant) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, string, plant.Plant) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, plant.Plant) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
