// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// MockGenerater is an autogenerated mock type for the Generater type
type MockGenerater struct {
	mock.Mock
}

// GenerateJWT provides a mock function with given fields: _a0
func (_m *MockGenerater) GenerateJWT(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
