// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package server

import (
	user "users/user"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthenticater is an autogenerated mock type for the Authenticater type
type MockAuthenticater struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: cred
func (_m *MockAuthenticater) Authenticate(cred user.Credentials) (string, error) {
	ret := _m.Called(cred)

	var r0 string
	if rf, ok := ret.Get(0).(func(user.Credentials) string); ok {
		r0 = rf(cred)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.Credentials) error); ok {
		r1 = rf(cred)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
