FROM node:12-alpine
RUN apk update && apk add g++ make python && rm -rf /var/cache/apk/*
WORKDIR /usr/src/app
ENV NODE_ENV=development
CMD [ -d "node_modules" ] && npm run start || npm ci && npm run start
