name: Deploy users app

on:
  push:
    branches: [main]
    paths:
      - "users/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: users

env:
  APP_NAME: users
  REGISTRY: eu.gcr.io

jobs:
  deploy:
    name: Deploy container to Google Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Get git sha
        run: echo "GIT_SHA=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build \
          -t "$REGISTRY"/"${{ secrets.GCP_PROJECT_ID }}"/"$APP_NAME":"$GIT_SHA" \
          --target=prod \
          ./

      - name: Push image
        run: docker push "$REGISTRY"/"${{ secrets.GCP_PROJECT_ID }}"/"$APP_NAME":"$GIT_SHA"

      - name: Install gcloud beta
        run: |
          gcloud components install beta

      - name: Deploy container
        run: |
          gcloud beta run deploy "$APP_NAME" \
          --allow-unauthenticated \
          --image="$REGISTRY"/"${{ secrets.GCP_PROJECT_ID }}"/"$APP_NAME":"$GIT_SHA" \
          --max-instances=4 \
          --platform=managed \
          --quiet \
          --region=europe-west1 \
          --update-secrets=APP_DOMAIN=APP_DOMAIN:latest,GCP_PROJECT_ID=GCP_PROJECT_ID:latest,USERS_DATABASE_URI=USERS_DATABASE_URI:latest,USERS_SECRET=USERS_SECRET:latest,WEB_URL=WEB_URL:latest
