FROM node:12-alpine as builder
RUN apk add --no-cache g++ make python
WORKDIR /usr/src/app
COPY app/package*.json ./
RUN npm ci
COPY app .env ./
ENV NODE_ENV=production
RUN npm run build

FROM nginx:stable-alpine
COPY proxy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /bin/www
CMD [ "nginx", "-g", "daemon off;" ]
