FROM node:12-alpine as app
RUN apk add --no-cache g++ make python
WORKDIR /usr/src/app
COPY app/package*.json ./
RUN npm ci
COPY app .env ./
ENV NODE_ENV=production
RUN npm run build

FROM golang:1-alpine AS server
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /usr/src/app
COPY server ./
RUN go build -ldflags '-s -w' main.go

FROM scratch
COPY --from=app /usr/src/app/dist ./dist
COPY --from=server /usr/src/app/main ./
ENTRYPOINT ["/main"]
